version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  prestashop:
    image: 'docker.io/bitnami/prestashop:1.7-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - PRESTASHOP_DATABASE_HOST=mariadb
      - PRESTASHOP_DATABASE_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - PRESTASHOP_HOST=${PRESTASHOP_HOST:-localhost}
      - WHITELABEL=${WHITELABEL:-AwesomePay}
      - PRESTASHOP_COUNTRY=${PRESTASHOP_COUNTRY:-us}
      - PRESTASHOP_LANGUAGE=${PRESTASHOP_LANGUAGE:-en}
      - PRESTASHOP_EMAIL=${PRESTASHOP_EMAIL:-user@example.com}
      - PRESTASHOP_PASSWORD=${PRESTASHOP_PASSWORD:-bitnami1}
      - HTTP_PORT=${HTTP_PORT:-8080}
      - HTTPS_PORT=${HTTPS_PORT:-8443}
      - HTTPS=false
      - REPOSITORY=${REPOSITORY:-https://github.com/user/repo}
      - BRANCH=${BRANCH:-master}
      - DEMO_CUSTOMER_PASSWORD=${DEMO_CUSTOMER_PASSWORD:-customer}
      - SHOP_PGC_URL=${SHOP_PGC_URL:-sandbox}
      - SHOP_PGC_USER=${SHOP_PGC_USER:-test-user}
      - SHOP_PGC_PASSWORD=${SHOP_PGC_PASSWORD:-test-pass}
      - SHOP_PGC_API_KEY=${SHOP_PGC_API_KEY:-key}
      - SHOP_PGC_SECRET=${SHOP_PGC_SECRET:-secret}
      - SHOP_PGC_INTEGRATION_KEY=${SHOP_PGC_INTEGRATION_KEY:-int_key}
      - SHOP_PGC_CC_SEAMLESS=${SHOP_PGC_CC_SEAMLESS:-0}
      - SHOP_PGC_CC_AMEX=${SHOP_PGC_CC_AMEX:-1}
      - SHOP_PGC_CC_DINERS=${SHOP_PGC_CC_DINERS:-1}
      - SHOP_PGC_CC_DISCOVER=${SHOP_PGC_CC_DISCOVER:-1}
      - SHOP_PGC_CC_JCB=${SHOP_PGC_CC_JCB:-1}
      - SHOP_PGC_CC_MAESTRO=${SHOP_PGC_CC_MAESTRO:-1}
      - SHOP_PGC_CC_MASTERCARD=${SHOP_PGC_CC_MASTERCARD:-1}
      - SHOP_PGC_CC_UNIONPAY=${SHOP_PGC_CC_UNIONPAY:-1}
      - SHOP_PGC_CC_VISA=${SHOP_PGC_CC_VISA:-1}
      - SHOP_PGC_CC_AMEX_SEAMLESS=${SHOP_PGC_CC_AMEX_SEAMLESS:-1}
      - SHOP_PGC_CC_DINERS_SEAMLESS=${SHOP_PGC_CC_DINERS_SEAMLESS:-1}
      - SHOP_PGC_CC_DISCOVER_SEAMLESS=${SHOP_PGC_CC_DISCOVER_SEAMLESS:-1}
      - SHOP_PGC_CC_JCB_SEAMLESS=${SHOP_PGC_CC_JCB_SEAMLESS:-0}
      - SHOP_PGC_CC_MAESTRO_SEAMLESS=${SHOP_PGC_CC_MAESTRO_SEAMLESS:-0}
      - SHOP_PGC_CC_MASTERCARD_SEAMLESS=${SHOP_PGC_CC_MASTERCARD_SEAMLESS:-0}
      - SHOP_PGC_CC_UNIONPAY_SEAMLESS=${SHOP_PGC_CC_UNIONPAY_SEAMLESS:-1}
      - SHOP_PGC_CC_VISA_SEAMLESS=${SHOP_PGC_CC_VISA_SEAMLESS:-1}
    volumes:
      - 'prestashop_data:/bitnami/prestashop'
      - './docker/configure.sh:/docker-entrypoint-init.d/configure.sh:ro'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local
