version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  prestashop:
    image: 'docker.io/bitnami/prestashop:1.7-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - PRESTASHOP_DATABASE_HOST=mariadb
      - PRESTASHOP_DATABASE_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - PRESTASHOP_HOST=${PRESTASHOP_HOST:-localhost}
      - WHITELABEL=${WHITELABEL:-AwesomePay}
      - PRESTASHOP_COUNTRY=${PRESTASHOP_COUNTRY:-us}
      - PRESTASHOP_LANGUAGE=${PRESTASHOP_LANGUAGE:-en}
      - PRESTASHOP_EMAIL=${PRESTASHOP_EMAIL:-user@example.com}
      - PRESTASHOP_PASSWORD=${PRESTASHOP_PASSWORD:-bitnami1}
      - HTTP_PORT=${HTTP_PORT:-8080}
      - HTTPS_PORT=${HTTPS_PORT:-8443}
    volumes:
      - 'prestashop_data:/bitnami/prestashop'
      - '.:/source_code:ro,consistent'
      - './docker/link_source.sh:/docker-entrypoint-init.d/link_source.sh:ro'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local
