version: '3'

services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
  prestashop:
    build: 'docker/'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD:-yes}
      - WHITELABEL=${WHITELABEL:-}
      - BITNAMI_APP_NAME=${BITNAMI_APP_NAME:-prestashop}
      - BITNAMI_IMAGE_VERSION=${BITNAMI_IMAGE_VERSION:-latest}
      - MARIADB_HOST=${MARIADB_HOST:-mariadb}
      - MARIADB_PORT_NUMBER=${MARIADB_PORT_NUMBER:-3306}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_ROOT_USER=${MARIADB_ROOT_USER:-root}
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=${MYSQL_CLIENT_CREATE_DATABASE_NAME}
      - MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=${MYSQL_CLIENT_CREATE_DATABASE_PASSWORD}
      - MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES=${MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES:-ALL}
      - MYSQL_CLIENT_CREATE_DATABASE_USER=${MYSQL_CLIENT_CREATE_DATABASE_USER}
      - PRESTASHOP_COOKIE_CHECK_IP=${PRESTASHOP_COOKIE_CHECK_IP:-yes}
      - PRESTASHOP_COUNTRY=${PRESTASHOP_COUNTRY:-us}
      - PRESTASHOP_DATABASE_NAME=${PRESTASHOP_DATABASE_NAME:-bitnami_prestashop}
      - PRESTASHOP_DATABASE_PASSWORD=${PRESTASHOP_DATABASE_PASSWORD}
      - PRESTASHOP_DATABASE_USER=${PRESTASHOP_DATABASE_USER:-bn_prestashop}
      - PRESTASHOP_EMAIL=${PRESTASHOP_EMAIL:-user@example.com}
      - PRESTASHOP_FIRST_NAME=${PRESTASHOP_FIRST_NAME:-Bitnami}
      - PRESTASHOP_HOST=${PRESTASHOP_HOST:-localhost}
      - PRESTASHOP_LANGUAGE=${PRESTASHOP_LANGUAGE:-en}
      - PRESTASHOP_LAST_NAME=${PRESTASHOP_LAST_NAME:-User}
      - PRESTASHOP_PASSWORD=${PRESTASHOP_PASSWORD:-bitnami1}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_PROTOCOL=${SMTP_PROTOCOL}
      - SMTP_USER=${SMTP_USER}
      - PRECONFIGURE=${PRECONFIGURE}
      - REPOSITORY=${REPOSITORY:-https://github.com/user/repo}
      - BRANCH=${BRANCH:-master}
      - SHOP_PGC_URL=${SHOP_PGC_URL:-sandbox}
      - SHOP_PGC_USER=${SHOP_PGC_USER:-test-user}
      - SHOP_PGC_PASSWORD=${SHOP_PGC_PASSWORD:-test-pass}
      - SHOP_PGC_API_KEY=${SHOP_PGC_API_KEY:-key}
      - SHOP_PGC_SECRET=${SHOP_PGC_SECRET:-secret}
      - SHOP_PGC_INTEGRATION_KEY=${SHOP_PGC_INTEGRATION_KEY:-int_key}
      - SHOP_PGC_CC_SEAMLESS=${SHOP_PGC_CC_SEAMLESS:-0}
      - SHOP_PGC_CC_AMEX=${SHOP_PGC_CC_AMEX:-1}
      - SHOP_PGC_CC_DINERS=${SHOP_PGC_CC_DINERS:-1}
      - SHOP_PGC_CC_DISCOVER=${SHOP_PGC_CC_DISCOVER:-1}
      - SHOP_PGC_CC_JCB=${SHOP_PGC_CC_JCB:-1}
      - SHOP_PGC_CC_MAESTRO=${SHOP_PGC_CC_MAESTRO:-1}
      - SHOP_PGC_CC_MASTERCARD=${SHOP_PGC_CC_MASTERCARD:-1}
      - SHOP_PGC_CC_UNIONPAY=${SHOP_PGC_CC_UNIOPNPAY:-1}
      - SHOP_PGC_CC_VISA=${SHOP_PGC_CC_VISA:-1}
      - SHOP_PGC_CC_AMEX_SEAMLESS=${SHOP_PGC_CC_AMEX_SEAMLESS:-1}
      - SHOP_PGC_CC_DINERS_SEAMLESS=${SHOP_PGC_CC_DINERS_SEAMLESS:-1}
      - SHOP_PGC_CC_DISCOVER_SEAMLESS=${SHOP_PGC_CC_DISCOVER_SEAMLESS:-1}
      - SHOP_PGC_CC_JCB_SEAMLESS=${SHOP_PGC_CC_JCB_SEAMLESS:-0}
      - SHOP_PGC_CC_MAESTRO_SEAMLESS=${SHOP_PGC_CC_MAESTRO_SEAMLESS:-0}
      - SHOP_PGC_CC_MASTERCARD_SEAMLESS=${SHOP_PGC_CC_MASTERCARD_SEAMLESS:-0}
      - SHOP_PGC_CC_UNIONPAY_SEAMLESS=${SHOP_PGC_CC_UNIOPNPAY_SEAMLESS:-1}
      - SHOP_PGC_CC_VISA_SEAMLESS=${SHOP_PGC_CC_VISA_SEAMLESS:-1}
      - BUILD_ARTIFACT=${BUILD_ARTIFACT:-undefined}
