version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    hostname: mariadb
    environment:
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
  prestashop:
    build: 'docker/'
    volumes:
      - '.:/source'
    ports:
      - '80:80'
      - '443:443'
    environment:
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
      - BITNAMI_APP_NAME=${BITNAMI_APP_NAME}
      - BITNAMI_IMAGE_VERSION=${BITNAMI_IMAGE_VERSION}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_PORT_NUMBER=${MARIADB_PORT_NUMBER}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_ROOT_USER=${MARIADB_ROOT_USER}
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=${MYSQL_CLIENT_CREATE_DATABASE_NAME}
      - MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=${MYSQL_CLIENT_CREATE_DATABASE_PASSWORD}
      - MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES=${MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES}
      - MYSQL_CLIENT_CREATE_DATABASE_USER=${MYSQL_CLIENT_CREATE_DATABASE_USER}
      - PRESTASHOP_COOKIE_CHECK_IP=${PRESTASHOP_COOKIE_CHECK_IP}
      - PRESTASHOP_COUNTRY=${PRESTASHOP_COUNTRY}
      - PRESTASHOP_DATABASE_NAME=${PRESTASHOP_DATABASE_NAME}
      - PRESTASHOP_DATABASE_PASSWORD=${PRESTASHOP_DATABASE_PASSWORD}
      - PRESTASHOP_DATABASE_USER=${PRESTASHOP_DATABASE_USER}
      - PRESTASHOP_EMAIL=${PRESTASHOP_EMAIL}
      - PRESTASHOP_FIRST_NAME=${PRESTASHOP_FIRST_NAME}
      - PRESTASHOP_HOST=${PRESTASHOP_HOST}
      - PRESTASHOP_LANGUAGE=${PRESTASHOP_LANGUAGE}
      - PRESTASHOP_LAST_NAME=${PRESTASHOP_LAST_NAME}
      - PRESTASHOP_PASSWORD=${PRESTASHOP_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_PROTOCOL=${SMTP_PROTOCOL}
      - SMTP_USER=${SMTP_USER}
      - PRECONFIGURE=${PRECONFIGURE}
      - REPOSITORY=${REPOSITORY}
      - BRANCH=${BRANCH}
      - SHOP_PGC_URL=${SHOP_PGC_URL}
      - SHOP_PGC_USER=${SHOP_PGC_USER}
      - SHOP_PGC_PASSWORD=${SHOP_PGC_PASSWORD}
      - SHOP_PGC_API_KEY=${SHOP_PGC_API_KEY}
      - SHOP_PGC_SECRET=${SHOP_PGC_SECRET}
      - SHOP_PGC_INTEGRATION_KEY=${SHOP_PGC_INTEGRATION_KEY}
      - SHOP_PGC_CC_SEAMLESS=${SHOP_PGC_CC_SEAMLESS}
      - SHOP_PGC_CC_AMEX=${SHOP_PGC_CC_AMEX}
      - SHOP_PGC_CC_DINERS=${SHOP_PGC_CC_DINERS}
      - SHOP_PGC_CC_DISCOVER=${SHOP_PGC_CC_DISCOVER}
      - SHOP_PGC_CC_JCB=${SHOP_PGC_CC_JCB}
      - SHOP_PGC_CC_MAESTRO=${SHOP_PGC_CC_MAESTRO}
      - SHOP_PGC_CC_MASTERCARD=${SHOP_PGC_CC_MASTERCARD}
      - SHOP_PGC_CC_UNIOPNPAY=${SHOP_PGC_CC_UNIOPNPAY}
      - SHOP_PGC_CC_VISA=${SHOP_PGC_CC_VISA}
      - SHOP_PGC_CC_AMEX_SEAMLESS=${SHOP_PGC_CC_AMEX_SEAMLESS}
      - SHOP_PGC_CC_DINERS_SEAMLESS=${SHOP_PGC_CC_DINERS_SEAMLESS}
      - SHOP_PGC_CC_DISCOVER_SEAMLESS=${SHOP_PGC_CC_DISCOVER_SEAMLESS}
      - SHOP_PGC_CC_JCB_SEAMLESS=${SHOP_PGC_CC_JCB_SEAMLESS}
      - SHOP_PGC_CC_MAESTRO_SEAMLESS=${SHOP_PGC_CC_MAESTRO_SEAMLESS}
      - SHOP_PGC_CC_MASTERCARD_SEAMLESS=${SHOP_PGC_CC_MASTERCARD_SEAMLESS}
      - SHOP_PGC_CC_UNIOPNPAY_SEAMLESS=${SHOP_PGC_CC_UNIOPNPAY_SEAMLESS}
      - SHOP_PGC_CC_VISA_SEAMLESS=${SHOP_PGC_CC_VISA_SEAMLESS}
    depends_on:
      - mariadb

volumes:
  undefined: